

services:
  postgres:
    image: postgres:16

    container_name: interviewiq-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: interviewiq

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile

    container_name: interviewiq-backend

    ports:
      - "8000:8000"

    working_dir: /app

    volumes:
      - .:/app

    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@postgres:5432/interviewiq

    depends_on:
      - postgres

    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: interviewiq-frontend

    ports:
      - "5173:5173"

    volumes:
      - ./frontend:/app
      - /app/node_modules

    depends_on:
      - backend

    restart: unless-stopped

volumes:
  postgres_data: